"""LLM-narrated weekly external market data — Section 六.2 / 六.3 / 六.4.

Three short single-paragraph slots, each generated by:
  1. web_search the relevant topic
  2. LLM writes a paragraph that mirrors the PDF's exact phrasing style
     (we anchor with the 5/4 example so register, sentence count, and
     unit notation stay consistent week-to-week)

3-tier output policy (revised 2026-05-12):
  Tier 1: target-week data found  →  write paragraph using those values
  Tier 2: only recent (≤14 days old) data found  →  write paragraph using
          that data and EXPLICITLY label the date in the sentence
          (e.g. "截至 5/9 ...")
  Tier 3: no usable data  →  output the single fixed sentence
          "<topic>本週尚未有公開報價資料。"
  Hard rule: never substitute 0, X, — for missing numbers.
"""
from __future__ import annotations

from datetime import date

from ..llm.openai_client import OpenAIClient
from .base import FetchResult, SourceAdapter, register
from .fengxing_finder import find_article as find_fengxing_article
from .steelnet_client import parse_intl_scrap_prices, polish_intl_scrap

_INTL_SCRAP_EXAMPLE = (
    "本週美國大船廢鋼無報價，美國貨櫃廢鋼上漲 1 元至 363 美元/噸，"
    "日本 2H 廢鋼本週持平為 385 美元/噸，"
    "澳洲鐵礦上漲 0.70 元至 109.75 美元/噸。"
)
_LME_COPPER_EXAMPLE = (
    "上週 115/4/24 收盤價 13,246.81 美元/噸，"
    "115/5/1 收盤價 12,916.40 美元/噸(當週下跌 330.41 美元/噸)。"
)


def _build_prompt(
    *,
    target_date: date,
    topic_zh: str,
    style_example: str,
    research_text: str,
    extra_rules: str = "",
) -> tuple[str, str]:
    system = (
        "你是台灣鋼鐵採購會議的市場數據分析員。你的任務是把網路上找到的"
        "本週鋼鐵相關行情，整理成一段「會議記錄」格式的純敘述段落。"
        "用語：繁體中文（台灣用語），半正式書面，含資訊量。"
    )
    user = f"""請依下方參考資料，撰寫一段 {topic_zh}（目標週包含 {target_date.isoformat()} 那一週）的本週行情敘述。

【寫作風格範例（必須完全比照句型、單位、漲跌字眼）】
{style_example}

【本週參考資料（你剛剛上網查到的）】
{research_text}

【輸出規則 — 3 階段 fallback，必須嚴格遵守】

優先順序 1：若參考資料有目標週（{target_date.isoformat()} 那週）的真實數字，
            直接撰寫段落。

優先順序 2：若沒有目標週數字，但有過去 14 天內的最近一週資料，
            **使用該資料**並在段落首句標明日期。
            範例寫法：「截至 5/9 公佈之資料，<topic>...」
            日期用阿拉伯數字 + 斜線（5/9，不要寫民國年）。

優先順序 3：若連近 14 天資料都沒有，輸出**這一句**就好（不要加其他內容）：
            「{topic_zh}本週尚未有公開報價資料。」

【允許的句式（whitelist — 只能用這些，不可造句）】
- 「<項目>持平為 N 美元/噸」 — 與上週相同
- 「<項目>上漲 D 元至 N 美元/噸」 — D 是漲幅，N 是新價，**D 必須小於 N**
- 「<項目>下跌 D 元至 N 美元/噸」 — D 是跌幅，N 是新價
- 「<項目>無報價」 — 該項目本週確實無公告
- 「<項目>無公開報價資料」 — 完全找不到

【絕對禁止的寫法（負面範例）】
- ❌「上漲 279 美元/噸至 279 美元/噸」（漲幅與新價相同 = 邏輯錯）
- ❌「無公開統一報價」「無集中報價」（編造詞，PDF 從來沒這寫法）
- ❌「指數值未明確」「資料尚未取得」（這種句子已用 fallback 句處理）
- ❌ 0、X、—、null、N/A 當數字
- ❌ markdown、項目符號、超連結、引文標記

【格式校驗】
寫完後請自我檢查：每個「上漲 D 元至 N」中 D 是否真的小於 N？若不是，請改寫。

{extra_rules}
"""
    return system, user


def _looks_garbage(text: str) -> bool:
    """Reject obvious failure modes that slipped past the prompt.

    Be CONSERVATIVE — better to keep an awkwardly-worded paragraph that
    contains real numbers than to discard everything and hand the user the
    bare fallback sentence. We only reject patterns that are clearly wrong.
    """
    if not text or len(text.strip()) < 10:
        return True
    # Hard wins: zero-as-placeholder is always wrong
    if "0 美元/噸" in text or "0元/噸" in text or "—/噸" in text or "null" in text:
        return True
    # "上漲 N 至 N" / "下跌 N 至 N" — same number both sides = nonsense
    import re
    for m in re.finditer(r"[上下][漲跌]\s*([\d,.]+)\s*[^/]{0,4}至\s*([\d,.]+)", text):
        if m.group(1) == m.group(2):
            return True
    return False


@register
class WeeklyMarketAdapter(SourceAdapter):
    name = "weekly_market"
    provides = [
        "intl_scrap_paragraph",
        "lme_copper_paragraph",
        "intl_jp2h_scrap_price",
        "intl_us_container_scrap_price",
    ]

    async def _fetch_intl_scrap_from_steelnet(
        self, target_date: date
    ) -> list[FetchResult]:
        """Reuse the Feng Hsin finder agent's pick to pull out:
          - 六.2 international scrap PARAGRAPH (text)
          - JP 2H + US container scrap PRICES (numeric, for 七.4 / 七.5)

        Returns a list of FetchResults (paragraph + 2 numerics).
        Returns [] on failure so the LLM path can take over the paragraph slot
        (numerics will simply not be produced this run).
        """
        try:
            parsed, picked, _trace = await find_fengxing_article(target_date)
        except Exception:
            return []
        if parsed is None or not parsed.intl_scrap_paragraph:
            return []
        url = picked["url"] if picked else ""
        source_url = f"https://www.steelnet.com.tw{url}"

        results: list[FetchResult] = []
        polished = polish_intl_scrap(parsed.intl_scrap_paragraph, target_date)
        results.append(FetchResult(
            slot_key="intl_scrap_paragraph",
            value=None,
            unit="text",
            raw_text=polished,
            source_url=source_url,
            confidence="medium",
        ))

        # Numeric extraction for 七.4 / 七.5 history tables
        prices = parse_intl_scrap_prices(parsed.intl_scrap_paragraph)
        for slot_key, val_key in (
            ("intl_jp2h_scrap_price",         "jp2h_scrap"),
            ("intl_us_container_scrap_price", "us_container_scrap"),
        ):
            v = prices.get(val_key)
            results.append(FetchResult(
                slot_key=slot_key,
                value=float(v) if v is not None else None,
                unit="美元/噸",
                raw_text=f"steelnet article 抽取自 intl_scrap 段落",
                source_url=source_url,
                confidence="high" if v is not None else "low",
            ))
        return results

    async def fetch(self, target_date: date) -> list[FetchResult]:
        client = OpenAIClient()
        results: list[FetchResult] = []

        # ── 六.2 國際廢鋼/鐵礦 — preferred source is steelnet.com.tw's
        # latest 豐興 weekly article, which always contains the canonical
        # sentence. Falls back to LLM web_search if that fails.
        intl_results = await self._fetch_intl_scrap_from_steelnet(target_date)
        results.extend(intl_results)
        # If steelnet path returned the paragraph slot, skip LLM fallback for it.
        intl_paragraph_filled = any(
            r.slot_key == "intl_scrap_paragraph" for r in intl_results
        )

        plan = [
            *([] if intl_paragraph_filled else [{
                "slot": "intl_scrap_paragraph",
                "topic": "國際廢鋼/鐵礦行情",
                "queries": [
                    f"美國貨櫃廢鋼 報價 {target_date.year}年{target_date.month}月 美元/噸",
                    f"日本2H 廢鋼 美元 {target_date.year}-{target_date.month:02d}",
                    f"澳洲 鐵礦 平台價 美元 {target_date.year}年{target_date.month}月",
                ],
                "example": _INTL_SCRAP_EXAMPLE,
                "extra": "說明：若美國大船廢鋼確實無報價，沿用「美國大船廢鋼無報價」字樣。",
            }]),
            {
                "slot": "lme_copper_paragraph",
                "topic": "LME 倫敦銅現貨收盤價",
                # Single focused query — multi-query confused the model previously
                "queries": [
                    f"LME copper cash settlement {target_date.year} May USD per ton "
                    f"weekly close",
                ],
                "example": _LME_COPPER_EXAMPLE,
                "extra": (
                    f"日期格式：民國年(如 {target_date.year - 1911})/月/日，"
                    f"例如 {target_date.year - 1911}/5/8。"
                    "段落必須包含上週、本週兩個收盤日的價格與週變動方向(上漲/下跌/持平)。"
                    "若搜尋結果只有單一日期，使用該日期+前一週同日；"
                    "若資料中只有月度均價沒有週收盤價，仍可使用，但要明標日期。"
                ),
            },
        ]

        for entry in plan:
            try:
                # Multiple search queries → richer source material
                research_chunks: list[str] = []
                citations: list[dict[str, str]] = []
                for q in entry["queries"]:
                    r = await client.web_search(q)
                    if r["text"]:
                        research_chunks.append(f"[query: {q}]\n{r['text']}")
                    citations.extend(r["citations"])

                combined_research = "\n\n".join(research_chunks) or "(無搜尋結果)"

                system, user = _build_prompt(
                    target_date=target_date,
                    topic_zh=entry["topic"],
                    style_example=entry["example"],
                    research_text=combined_research,
                    extra_rules=entry["extra"],
                )
                paragraph = (await client.chat(system, user, max_tokens=900)).strip()

                # Sanity check — reject obvious 0-填充 / empty
                if _looks_garbage(paragraph):
                    paragraph = f"{entry['topic']}本週尚未有公開報價資料。"
                    confidence = "low"
                else:
                    confidence = "medium"

                # Dedup citations by url
                seen = set()
                deduped = []
                for c in citations:
                    u = c.get("url", "")
                    if u and u not in seen:
                        seen.add(u)
                        deduped.append(c)

                results.append(FetchResult(
                    slot_key=entry["slot"],
                    value=None,
                    unit="text",
                    raw_text=paragraph,
                    source_url=deduped[0]["url"] if deduped else "",
                    confidence=confidence,
                ))
            except Exception as e:
                results.append(FetchResult(
                    slot_key=entry["slot"],
                    value=None,
                    unit="text",
                    raw_text=(
                        f"{entry['topic']}本週尚未有公開報價資料。"
                        f"  [error: {type(e).__name__}]"
                    ),
                    source_url="",
                    confidence="low",
                ))

        return results
