"""add admin role token_version index token_count

Revision ID: 9431d4e5169d
Revises: da6b9189693e
Create Date: 2026-05-07 10:28:36.286363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9431d4e5169d'
down_revision: Union[str, Sequence[str], None] = 'da6b9189693e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('idx_conv_user_updated', ['user_id', 'updated_at'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('role', sa.String(length=20), nullable=False, server_default='user')
        )
        batch_op.add_column(
            sa.Column('token_version', sa.Integer(), nullable=False, server_default='0')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('token_version')
        batch_op.drop_column('role')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('token_count')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('idx_conv_user_updated')

    # ### end Alembic commands ###
